// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfAuDca0caznnspJyWlF_p4malk12lS0A',
    appId: '1:496083964307:web:185d1f748c680b0d759866',
    messagingSenderId: '496083964307',
    projectId: 'rich-furniture-43b22',
    authDomain: 'rich-furniture-43b22.firebaseapp.com',
    storageBucket: 'rich-furniture-43b22.appspot.com',
    measurementId: 'G-ZPLVTG2GDJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBc7rhwJgfH3f5geBvZil5Kk2BRYNE6EEA',
    appId: '1:496083964307:android:4d4d2a06f02cd781759866',
    messagingSenderId: '496083964307',
    projectId: 'rich-furniture-43b22',
    storageBucket: 'rich-furniture-43b22.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkPvRdixlGqu6WcxqvKAsfvVZMEoIzICk',
    appId: '1:496083964307:ios:4a9901a649f7cfe8759866',
    messagingSenderId: '496083964307',
    projectId: 'rich-furniture-43b22',
    storageBucket: 'rich-furniture-43b22.appspot.com',
    iosBundleId: 'com.example.richFurniture',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkPvRdixlGqu6WcxqvKAsfvVZMEoIzICk',
    appId: '1:496083964307:ios:4a9901a649f7cfe8759866',
    messagingSenderId: '496083964307',
    projectId: 'rich-furniture-43b22',
    storageBucket: 'rich-furniture-43b22.appspot.com',
    iosBundleId: 'com.example.richFurniture',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfAuDca0caznnspJyWlF_p4malk12lS0A',
    appId: '1:496083964307:web:08f1158a4739db4a759866',
    messagingSenderId: '496083964307',
    projectId: 'rich-furniture-43b22',
    authDomain: 'rich-furniture-43b22.firebaseapp.com',
    storageBucket: 'rich-furniture-43b22.appspot.com',
    measurementId: 'G-66BJQ51QD3',
  );
}
